Salvoxia/immich-folder-album-creator

immich_auto_album.py
Useful in environments with self-signed certificates
=> Add option to disable SSL verification

README.md, docker/immich_auto_album.sh, immich_auto_album.py, requirements.txt
- Added option to skip SSL verification
- Added option to ignore folders, sub-folder sequences or files
=> Merge features from Dev branch

README.md, docker/immich_auto_album.sh, immich_auto_album.py, requirements.txt
Added `-f / --path-filter` option / `PATH_FILTER` Docker environment variable to pass a GLOB-style pattern for filtering assets before album creation
=> Feature: Path Filter

immich_auto_album.py
Added option to set the thumbnail of the created/updated albums to first, last or random image.
=> added feature to set thumbnail for album

immich_auto_album.py
Introduced common function to check API responses for errors and log the payload (if any)
=> Enhancement: API Error Logging

immich_auto_album.py
Fixed finding assets in archive if flag was set or --mode was anything but CREATE
=> Fix: Find Assets in Archive

.github/workflows/ci.yaml, .pylintrc, README.md, immich_auto_album.py
- Refactored code to satisfy pylint
- Add Github Action to run pylint on push
=> chore: Add pylint

immich_auto_album.py
Verify album levels range is failing.  This is my first pull request.  Apologies if this is not the correct way to do a PR.
=> Bug Fix: Verify album levels range check incorrect

README.md, immich_auto_album.py
- Added section for Mass Updating Album Properties
- Changed all CLI examples to multi-line for better readability
- Added dedicated docker-compose examples for using secrets file and passing the API key directly
=> Readme Enhancements

README.md
Updated compatibility statement with v1.124.x
=> README compatibility statement for v1.1.124.x

immich_auto_album.py
=> Fix: Regression: Fixed --share-with <name>=<role> syntax

docker/immich_auto_album.sh
With this change, ranges can be used also in docker container
=> fix ALBUM_LEVELS ranges in docker container

immich_auto_album.py
Workaround for https://github.com/immich-app/immich/issues/16401 / https://github.com/immich-app/immich/issues/16818
=> Fix/Ignore Live Photo Video Components

README.md
Updated compatibility statement with version 1.129.x
=> README: Updated compatibility statement with version 1.129.x

README.md
compatibility statement for v1.1.130.x
=> README compatibility statement for v1.1.130.x

README.md
Clarified Immich versions for which discovering offline assets was broken, thus --sync-mode 2 did not work
=> README: Sync Mode

README.md
compatibility statement for v1.131.x
=> README Compatibility Statement for v1.131.x

.github/workflows/ci.yaml, immich_auto_album.py
Hi
just removed some redundant code and little optimization - more to come...
=> Minor optimization

immich_auto_album.py
=> stupid ad-hoc linting mistake

immich_auto_album.py
=> Fix/Album Level Range: Skip out of range assets

README.md
Compatibility statement for v1.1.134.x
=>  README Compatibility Statement for v1.134.x

README.md
Added section detailing required API key permissions as of Immich Server v1.135.x
=> README: Required API Key permissions

README.md
Added README compatibility statement for v1.141.x
=> chore: README compatibility statement for v1.142.x
